require: rubocop-rails

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 120

Layout/LineLength:
  Max: 300

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Rails/HelperInstanceVariable:  
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Lint/UselessAssignment:
 Enabled: false

Rails/OutputSafety:
  Enabled: false